version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  ping:
    image: irfan7771/pythonapp:v1
    container_name: pythonapp
    expose:
      - "5000"

