---
- hosts: " {{ target }} "
  become: yes
  tasks:
    - name: Analyzing environement form file...
      shell: grep -ow 'ping' userdata.txt
      register: presence
    - name: Copy a "docker-compose" file on the remote machine
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: /home/irfanshaikh/ansible/docker-compose.yml
        remote_src: yes
      when: presence.stdout == "dev"
    - name: "Docker compose development deployment for development"
      ansible.builtin.shell:
         cmd: docker-compose up {{ presence }}         
         chdir: /opt
         remote_src: yes
         executable: /usr/local/bin/
      when: presence.stdout == "dev"
    - name: "docker compose up for  prod"
      ansible.builtin.shell: docker-compose up  {{ presence }}
      when: presence.stdout == "prod"
    - name: "docker compose up for prod-1"
      ansible.builtin.shell: /usr/local/bin/docker-compose up -d {{ presence }}
      when: presence.stdout == "ping"


